title = "Seven steps"
theme = "hemingway"
baseurl = "http://blog.trevoke.net"
languageCode = "en-us"
copyright = "&copy; <a href=\"https://github.com/trevoke\">Aldric Giacomoni</a> 2017"

[params]

[params.highlight]
style = "arduino-light"
languages = ["ruby", "elixir", "javascript", "erlang"]

[[params.social]]
url = "https://github.com/trevoke"
fa_icon = "fa-github"

[[params.social]]

url = "https://twitter.com/trevoke"
fa_icon = "fa-twitter"
