#+TITLE:       Getting good at web page layout
#+AUTHOR:      Aldric Giacomoni
#+EMAIL:       trevoke@gmail.com
#+DATE: 2016-04-03
#+DRAFT: t

Read diveintohtml5.info for resources on the latest HTML5 tags. Use caniuse.com to know on how many browsers features work.
Anything that gets you playing with the box model is good. Get to an understanding of how margin and padding interact with each other on contiguous elements. Get a feel for how nested elements behave differently when their position is changed (e.g. position absolute nested within position relative).
Practice creating your own typographical lexicon and find out how to make things regular (reuse h1 / h2 / h3 if it makes sense, rather than creating a ton of “header-like” classes”).

Finally, look into accessibility features and responsive design, and practice with actual content, because as much as a designer has to care about the content when they design, as much someone working with the front-end needs to be aware of the consequences of various content (what happens if this is empty? what if it’s 300 characters long?)
