#+TITLE: Country alert levels
#+DATE: 2010-01-20
#+TAGS: funny

Let's break the monotony with something funny:

The English are feeling the pinch in relation to recent terrorist threats? and have raised their security level from "Miffed" to "Peeved." Soon, ?though, security levels may be raised yet again to "Irritated" or even "A? Bit Cross." The English have not been "A Bit Cross" since the blitz in 1940 ?when tea supplies all but ran out.

Terrorists have been re-categorized from ?"Tiresome" to a "Bloody Nuisance." The last time the British issued a? "Bloody Nuisance" warning level was in 1588 when threatened by the Spanish Armada.??

The Scots raised their threat level from "Pissed Off" to "Let's get the? Bastards" They don't have any other levels. This is the reason they have? been used on the front line of the British army for the last 300 years.

??The French government announced yesterday that it has raised its terror ?alert level from "Run" to "Hide". The only two higher levels in France are? "Collaborate" and "Surrender." The rise was precipitated by a recent fire?that destroyed France's white flag factory, effectively paralyzing the ?country's military capability.

It's not only the French who are on a? heightened level of alert.
Italy has increased the alert level from "Shout ?loudly and excitedly" to "Elaborate Military Posturing." Two more levels ?remain: "Ineffective Combat Operations" and "Change Sides."?

?The Germans also increased their alert state from "Disdainful Arrogance" to?"Dress in Uniform and Sing Marching Songs." They also have two higher? levels: "Invade a Neighbour" and "Lose".?

?Belgians, on the other hand, are all on holiday as usual, and the only ?threat they are worried about is NATO pulling out of Brussels.

??The Spanish are all excited to see their new submarines ready to deploy. ?These beautifully designed subs have glass bottoms so the new Spanish navy ?can get a really good look at the old Spanish navy.??

Americans meanwhile and as usual are carrying out pre-emptive strikes, on?all of their allies, just in case.?

?And in the southern hemisphere...

??New Zealand has also raised its security levels - from "baaa" to "BAAAA!". ?Due to continuing defense cutbacks (the airforce being a squadron of spotty ?teenagers flying paper aeroplanes and the navy some toy boats in the Prime?Minister's bath), New Zealand only has one more level of escalation, which? is "I hope Australia will come and rescue us".??

Australia , meanwhile, has raised its security level from "No worries" to?"She'll be right, mate". Three more escalation levels remain: "Crikey!', "I ?think we'll need to cancel the barbie this weekend" and "The barbie is? cancelled". So far no situation has ever warranted use of the final? escalation level.

