#+TITLE: The schism in martial training paradigms
#+DATE: 2012-06-19
#+CATEGORIES: martial-arts
#+TAGS: wrist-grab punches boxing drills

<h2>You're training wrong! No, YOU're training wrong!</h2>

A recent set of conversations have led me to examine the major difference in martial training. I'm going to start by separating training in two categories, making an imperfect black-and-white model of the martial world:

<ul>
        <li>Traditional eastern training</li>
        <li>Jeet Kune Do-like training</li>
</ul>

Now, let's start to talk about the <em><strong>PURPOSE</strong></em><strong><em> </em></strong>of each, in a fairly roundabout way.

Let's talk about the traditional drill which has become sort of a standard: "Grab my wrist". The joint lock. Many people have images of rows of people in white uniforms with colored belts, all standing there, grabbing one of their partner's wrists, and waiting. Then the partner tries to do some kind of fancy something-or-other and ideally, the person grabbing the wrist is now very sorry for themselves.

Well, there's a clear problem with that drill, isn't there? In fact, there's a LOT of problems. Let's talk about them.
<h2>1. Who in their right mind would grab someone's wrist?</h2>
Okay, good point. You win. It's a silly drill. No, but seriously - superficially, that's dumb, unless maybe you were trying to take some weaker person away with you - and in that case, you'd also want to make sure they weren't making sound. So, why grab someone's wrist?

Let's look at it a little differently. People use their hands often, every day, for a number of fairly varied tasks. They use their hands with purpose, like grabbing a mug, drinking from it, driving, texting, typing on a keyboard, opening a door... People are used to relating to the world through their hands. It is more natural than, say, lying down on the ground and trying to get a knee or ankle lock on someone with both of your feet, so it is an easier starting point. So there's the grabbing part.

Why the wrist? Well, what if someone were trying to take out a knife to stab you, wouldn't you try and stop them? Possibly by grabbing their wrist? 
<h2>2. Why grab someone's wrist and let them do whatever they want?</h2>
Yeah, I mean, why? They're gonna start moving your hand, arm, wrist, elbow, shoulder, body, this way and that, and you're just gonna let it happen? What kind of an idiot are you?

Well, for starters, as the person portraying the 'attacker', it is not currently your role to beat up the other person. See, they are the receiver, so it is their turn to practice, with comfortable slowness and smoothness, a potentially complex move which may require subtle manipulation (moving the body in just the right way to get the desired result). So you should let them experiment until they are comfortable with the move. That's the whole point. Maybe now is a good time to explain why people need to get comfortable - the stuff that you're practicing actually can hurt you. I know, kind of a shocker, right? Performed improperly, on an opponent that is trying to resist, forcing to try and get the desired result, one can truly do long-lasting damage to a partner. The point of a partner is to train with them for a long time, so this defeats the purpose a bit.
<h2>3. Why grab someone's wrist and not have a follow-up move?</h2>
I hear this all the time: if you're grabbing someone, you're probably pulling them into a punch with the other hand - or worse (knife, whatever). Yes. Great. Not for beginner practice. The previous point applies - people need to get comfortable with what they're doing FIRST.  Follow-up moves start to play with intermediate-to-advanced concepts which should only be brought in later, when both people have an understanding of when one has failed to apply the technique, so no useless forcing happens. Some of these concepts are stepping, angles, combinations,  directional shifts
<h2>4. Why stay locked when they have a lock on you?</h2>
This fourth point is a little subtle: locks are dynamic things. If someone puts you in a lock and they stop applying force in some direction, then you can move out of the lock. And again,

&nbsp;

Okay, so I waxed lyrical about the fact that the wrist grab is a beginner's move. Oh wait, no, I didn't. Hang on a sec.. What I said was that the most basic way of practicing the wrist grab, the safest way, the way that leads to growth, BASED ON THE TRADITIONAL TRAINING SYSTEM, is a static exercise, removing most of the variables of combat.

Yeah... And then what? Well, once you're comfortable with static, you begin to add energy to it, and that's when it truly comes alive. Pull, push, add a strike, add a step.. All those things get practiced until the student is comfortable. And then what? Are you gonna start sparring and suddenly grab someone's wrist? Well... Probably not. You'd probably end up getting punched in the face, and you'd deserve it, too.

The neat thing about this practice is that it teaches you to feel how someone else applies their force in a direction (for which I will use the word 'energy' from now on). The tricky thing about this practice is that it only works by surprise. And the hard thing about it is that you can really mess up someone's body if you do it suddenly enough.

Yeah.. But wait! I just said you weren't gonna do it when sparring! Well, no, you're not. But if you are going to do it, someone will have grabbed you -- or sent energy in some shape in your direction (e.g. a punch), and that will be your answer. It will be swift, it will be sudden, and with the correct precision, it will send the poor sod on the floor. And what if it fails? Well, you can run, you can try to hit the guy a lot, or you could go for the subtler option, which requires more years of training - switch to another lock on the next available joint.

&nbsp;

Okay, now I bet you're saying that I'm just giving you the runaround. I talked about purpose, somewhere way above, and I haven't mentioned anything about it since! That's true. But I was also setting up the stage. What is the purpose of the traditional training? The purpose of traditional training is <strong>NOT</strong> to make you an efficient fighter <strong>QUICKLY</strong>. Traditional training should be making you look inward and discover the connection between your mind and body, helping you discover who you really are and what your illusions are. As the training progresses, it gets increasingly hard and subtle, therefore refining you and your understanding of your place in society through the study of conflict.

Gosh, so many big words. How much what I just said is true? Eh... Nowadays, it depends on the student.

&nbsp;

Someone I was talking to recently compared "grab the wrist" to "we can both throw jabs and our only defense is slipping".

Well, let's apply the same concepts - though I won't make as big a deal of them since you saw them above.

1) Why would you just jab? Well, why not. Maybe you can knock the guy out, or explode his nose, or just jab four times before he realizes you're taking the initiative / preempting. It's a strike and it's got chances to be effective. Besides, throwing multiple jabs is a good drill to build up your shoulder muscles and practice targeted striking!

2) Why jab and let them do whatever they want? Well.. Alright, in this drill, we're not. We jab and they only get to slip. This is a strict drill, working hips, legs, maybe stepping, maybe parrying with the hands. This is all good stuff.

3) Why jab and not have a follow-up move? Well, because it's a drill, duh! We're just doing this over and over, working on very specific skills that directly and obviously relate to what I call a level one confrontation: strikes. Hell, it's worked for boxers. Nah.. This analogy is flawed. Boxers don't use their legs for anything but power generation. No kicks, no trips.

4) Why not counter when you slip? Well.. That would end the drill, and it's not the point. You'd have a drill for counters. These drills are, of course, just as artificial as "grab my wrist". The thing is, some people like them better. They need to move.

&nbsp;

In general, I've found the camp to be split between people who prefer the "grab my wrist" context and people who prefer "jab and slip". Both drills get practiced by both people, colored by the environment, but one side matches their personality better. "Grab my wrist" is not realistic! They say. "Jab and slip" doesn't develop your sensitivity! They say.

Here's what one guy had to say about it.. You may have heard of him, his name is Bruce Lee, and he wrote that book called "Tao of Jeet Kune Do":
<blockquote>"Instead of facing combat in its suchness, then, most systems of martial art accumulate a "fancy mess" that distorts and cramps their practitioners and distracts them from the actual reality of combat, which is simple and direct. Instead of going immediately to the heart of things, flowery forms (organized despair) and artificial techniques are ritualistically practiced to simulate actual combat. Thus, instead of 'being' in combat these practitioners are 'doing' something 'about' combat.
"Worse still, super mental power and spiritual this and spiritual that are desperately incorporated until these practitioners drift further and further into mystery and abstraction. All such things are futile attempts to arrest and fix the ever-changing movements in combat and to dissect and analyze them like a corpse." (p. 14)
"Forms are vain repetitions which offer an orderly and beautiful escape from self-knowledge with an alive opponent." (p. 16)</blockquote>
While I agree with some of it, I think there is a fundamental flaw in trying to reject such static training: it develops a fundamental and critical awareness and sensitivity which becomes reflexive over time. I've watched a 70+ year-old man move another guy around like a volley ball with impressive speed and precision, and his training had been extremely traditional (though, granted, over a period of fifty years or more).


I think that when people criticize a drill, they're really criticizing instructors who have no understanding of the depth of the drill - or, reflexively, criticizing themselves for not having a deep enough understanding of the drill, an unwillingness to practice. <em>No think. No talk. Train.</em>

On that note, I stop my tongue-fu.
