#+TITLE: Monday night training
#+DATE: 2009-11-26 14:17:52 UTC
#+PUBLISHDATE: 2009-11-26
#+DRAFT: t
#+TAGS: untagged
#+DESCRIPTION: I received an email from sensei on Monday

I received an email from sensei on Monday (sent to every student) - if you'll be here tonight, bring your fighting gear. Uh-oh. Her sensei was there and taught a few classes, including the adults. The entire class turned out to be pretty much a blur of drills. I'll be able to dredge them out of my body memory, I think.
A drill about basics - chain two basics together, using shifting. Then up to six basics together, by series of two.
A couple of kicking drills. A few fighting drills - these are important. shift, step back, kick, finish, disengage.
Come in and jam, elbow, finish.
I am obfuscating these on purpose. 
This was a harder training session than I've experienced in a while, as evidenced by the appearance after 40-some hours of a slight tightness in my upper abs and shoulder muscles.. Oh, and the fact that my lower legs were one solid body, instead of having a freely moving calf muscle.

Of course, I was supposed to the student in the best shape, so I wonder how the others did feel. This wasn't particularly hard on my mind, just a little bit past my comfort zone.. I do feel like I am more aware that I can stand more than I think. Was my willpower muscle flexed? It seems like it was.