#+TITLE: Shu ha ri and evolution of a skill
#+DATE: 2014-02-18
#+CATEGORIES: martial-arts process
#+TAGS: shu-ha-ri learning growth

Shu Ha Ri comes from the world of Japanese Noh theater, and has been since attached to the world of martial arts and <a title="Alistair Cockburn's words on Shu Ha Ri" href="http://alistair.cockburn.us/Shu+Ha+Ri">Agile development</a>. Roughly, "shu ha ri" means "learn / detach / transcend". The link has some words about that meaning. I'd like to talk about my particular take on Shu Ha Ri, which came out of a parking-lot
conversation with a martial arts teacher friend of mine:

<ol>
        <li>Shu. Do the damn technique.</li>
        <li>Ha. Vary the damn technique.</li>
        <li>Ri. You don't need the damn technique.</li>
</ol>

And here is the slightly longer interpretation.

SHU: right foot in front, grab the left wrist from the front with the right hand. Study the particular wrist escape that has been taught in this situation. In Agile words: be rigorous about your Agile practice. Do it "dumbly" until you get good at it and everyone in your team is OK with it.

HA: grab some wrist in some way, and play with that wrist escape. Add footwork. See what works and what doesn't. In Agile words, now's the time to see when is a good time for standup, what should be said, how long the standup should take. Or maybe change the beginning of the iteration; or how you do story breakdown. Pick ONE variable, change it, and learn from what happened, whether it worked or it didn't ("worked" is a variable term, at this point of your growth, you'll know it well enough when you see it).

RI: It's not about a wrist grab anymore, but about much more fundamental principles. Detached from the technique, or the labels of "wrist grab" and "wrist escape", it simply becomes about the right movement producing the right result ("right" is a variable term, at this point of your growth, you'll know it without seeing it). In Agile words, you understand why a standup is just one example of a practical application of the Agile principles, and you are able to create custom applications of the principle for your teams, so that they can be Agile in the way that works best for them.


You may notice that HA and RI seem just a little similar from the point of vagueness: you'll know it when you see it. It takes a long time to work through HA, and the line between the two is fairly definite, but hard to find. So practice, practice, practice. Or rather, perfect practice, perfect practice, perfect practice. And check your ego at the door.
