#+TITLE: The Litany Against Fear
#+DATE: 2013-11-18
#+categories[]: philosophy
#+tags[]: litany-against-fear meditation

So, the litany against fear goes like this:

#+begin_quote
I must not fear. Fear is the mind-killer. Fear is the little-death that brings total obliteration. I will face my fear. I will permit it to pass over me and through me. And when it has gone past I will turn the inner eye to see its path. Where the fear has gone there will be nothing. Only I will remain.
#+end_quote

And here's my attempt at an interpretation of its meaning.

*** *I will not fear. Fear is the mind-killer. Fear is the little-death that brings total obliteration.*

While it is a natural thing to feel fear and be afraid, I will not give in to it and become the fear. Becoming the fear means to revert to the basest instincts that we have, usually fight-or-flight, and then one's actions are only concerned with survival. There is none of the higher reasoning left. This can be expanded slightly by adding another quote from Dune, from the scene where Paul meets the Gom Jabbar. The Reverend Mother says,

#+begin_quote
You've heard of animals chewing off a leg to escape a trap. There's an animal kind of trick. A human would remain in the trap, endure the pain, feigning death that he might kill the trapper and remove a threat to his kind.
#+end_quote

We're talking, fundamentally, about a different level of perception. Your existence is not about yourself, it is about survival of your species.

*** *I will face my fear. I will allow it to pass over me and through me.*

I will accept that I am afraid. This means recognizing that emotions are a part of one's self, and not refusing to acknowledge a single part of one's identity. I will look to my fear with compassion and kindness, for it is a part of me. Looking to any part of me with less than compassion of kindness is much like hating myself, and that's just not productive.

I will allow my fear, as an emotion, to wash through my body and run its course, so that the hormonal and nervous systems in my body do not get overworked or damaged by unnatural resistance to a normal behavior. I will also allow the fear to talk to the brain, so I can communicate with the fear, examine where it came from and, if necessary, figure out why it came up, so that the origin may be extirpated if necessary.

*** *And when it has gone past, I will turn the inner eye on its path. Where the fear has gone, there will be nothing. Only I will remain.*

Just like death, fear leaves a mark on the ego, on the self. A person can end up damaged, responding only to the behaviors implanted by the fear response, instead of responding to the actual situations with which they are faced. Once the fear is done, and the situation is resolved, I will examine my self, and realize that my self is still there, and did not get damaged by the fear. I will realize that the fear, like the tide on the beach, came and went, and like the ocean, I am unmoved by the tide. Thus, I will reinforce the behavior, so that next time, this is even easier, because I have even more trust in how this works, until it becomes an automatic response.

*** Conclusion
This is a deep and powerful mantra, which hints at tremendous self-control and self-awareness. As always, the first step is awareness.
