#+TITLE: Hear no evil. See no evil. Speak no evil.
#+DATE: 2012-07-12 22:00:57 UTC
#+PUBLISHDATE: 2012-07-15
#+DRAFT: t
#+TAGS: untagged
#+DESCRIPTION: I had an epiphany tonight about something

I had an epiphany tonight about something that just about everyone knows: the three monkeys. And I wanted to share it with you.

The three monkeys are accompanied by the words: "See no evil. Hear no evil. Speak no evil." The funny thing is that one monkey is covering his eyes, one monkey is covering his ears, and one monkey is covering his mouth! Let's examine that for a second.

See no evil -&gt; Don't look
Hear no evil -&gt; Don't listen
Speak no evil -&gt; Don't talk

That's kind of an odd transposition, isn't it? How does it work?
Well, it doesn't. That's the point. They're monkeys: they're not people. They misunderstand. They figure that the easiest way to see no evil is to close your eyes: that way you can't see the evil that people do. They figure you should just not listen: so you can't hear the evil people say. And they figure the safest thing to do is not talk: it means you can't say anything evil.

But if you go through life with your eyes closed, your ears closed, and your mouth closed, you're not a good part of society. Your mind isn't working, and you're going to miss on the beauty of life.

Here's the trick.

See no evil and hear no evil have to do with the same thing: it's not WHAT you see/hear, it's HOW you see/hear. Don't judge. Speak no evil has to do with what's inside of you too: why are you saying what you're saying?

Hearing and Seeing are receiving actions, but Speaking is an emitting action. You can influence others with that action, and so you must be sure your words aren't coming from negative thoughts.

So hang on, how can we straighten this out? If we're not judging what's coming in, why are we judging what's coming out? Well, here's the next trick: you're not JUDGING. You're accepting. Seeing, Hearing and Speaking: these are yin and yang manifestations of love. Basically, you should always act out of love. You should be love.

What an odd sentence. "You should be love". Unfortunately, this is pretty much where all the esoteric texts also stop, because it's one of those things you have to realize for yourself.