#+TITLE: Tonight's training (good AGAIN!)
#+DATE: 2009-09-23
#+categories[]: martial-arts
#+tags[]: sparring

It was surprisingly good. I didn't feel very good tonight - slight headache, slight tingle in the throat. I wasn't going to stay for my class, just help teach and then go home, get tea, get sleep.. But <!--more-->only two other adults showed up and sensei was upstairs, so I started the class and took it easy on the calisthenics and the stretches. Those two adults are the two with the most issues of muscle contractions (as in, they have no idea what relaxing means). So I started off real, real easy, taking them back to the basics.

I spent the entire class putting no emphasis on heavy force (or rather, an emphasis on the lack of such). All I wanted was high chambers, and then high and with the correct angle, and then high + the correct angle + tight chambers, and then that plus the kicks. So it was five reps of just chambers, then the other side, then five reps of loose, relaxed chambers on the first side, then the same thing on the other side.

I did that on all the basic kicks, which took about 30 minutes. It was time very well spent, because I noticed marked improvement in both students as well as in my own body.
Sensei came down about halfway through and listened, then watched. She gave a few key corrections to the students and one to me, and then afterwards, she told me I'd done a good thing! WOO HOO!


All in all, the light exercise gave me a light workout, keeping my body temperature up without exhausting me.. Now I'm home, sipping Silver Needle tea in a "Mug of vi" from Thinkgeek. Life is good, right this moment.
