#+TITLE: New position at Cyrus
#+DATE: 2010-04-22
#+TAGS: cyrus innovation

On Monday, April 26th, I am starting a new job at Cyrus Innovation. It may well be fair that I am starting a new career - it's a hop, skip and jump for me. I'm switching from Systems Administration / Tech Support / Hell desk (not a typo, sadly) to Development / Programming.

I am very much looking forward to it. It means a hobby/job switch: I will now do sysadmin stuff as a hobby, and programming as a full-time job. We'll see how it works out :)

I remember looking up to the early programmers in awe - they were wizards, and their skill probably couldn't be equaled, reached, or even, likely, attempted. Then came Ruby. There will always be master hackers - but with Ruby, and its community, it seems that everything is easily at hand. People care about making code elegant and accessible. Things which would take lines and lines of codes in other languages are usually between one and four lines. It's powerful. And it's not difficult. The most arcane and powerful elements of the language are ... Accessible. The code doesn't get in the way of the mental gymnastics.

I'm sure I'll be using other languages - it's a good way to grow, after all - and I look forward to it. Finally: a place where I can, and will, always be learning.
