#+TITLE: AT&T: A ten-year customer says goodbye
#+DATE: 2011-05-10 22:13:40 UTC
#+PUBLISHDATE: 2011-05-31
#+DRAFT: t
#+TAGS: untagged
#+DESCRIPTION: I just moved into a new apartment where t

I just moved into a new apartment where the AT&amp;T reception is, well, atrocious. Still, I like AT&amp;T, so I'm dragging my feet to switch to Verizon (or something else).

Today, I spoke in live chat to some AT&amp;T employee. I believe the name was Monica Garnett but I could be wrong -- and it probably doesn't matter. My issue was that I didn't seem to have a mailbox for my phone number. She says my data plan is unsupported for smart phones.

... Wait, what? I've been using this data plan for over a year with this phone. Maybe I never got voicemail, but who cares! It WORKED. I had unlimited text and unlimited data. Now, yes, I know, this plan had been removed and AT&amp;T wasn't offering it anymore, but I am an existing customer, I get the perk of keeping that, right?

... No. I was told I could switch to their 200Mb/month or 2Gb/month plan, which I did, but what I wasn't told is that THESE PLANS DO NOT INCLUDE MESSAGING.

Now, I want to fix this. I got screwed by a company, big whoop, whatever, I'll just limit myself a little. THE WEBSITE DOES NOT GIVE ME REASONABLE OPTIONS. I can get unlimited text, or unlimited text with any mobile-to-mobile calling, or 1000 texts.

I could pay $15 for 200 megs and $10 for 1000 texts, and then I'd have $25 -- which is, $5 less than unlimited data and unlimited texts. Huh. NO.

I could pay $25 for 2Gb and $10 for 1000 texts, or $20 for unlimited texts. So .. $35 or $45? NO.

Seriously? So I have to pay MORE now to have LESS than I used to have? Well, goodbye, AT&amp;T. Guess who's going to go say hi to another phone service provider tomorrow?