#+TITLE: iReadmammo : easy DB source / DICOM node config
#+DATE: 2009-01-04 22:11:06 UTC
#+PUBLISHDATE: 2009-01-04
#+DRAFT: t
#+TAGS: untagged
#+DESCRIPTION: Cedara iReadmammo (now Merge Mammo) is a 

Cedara iReadmammo (now Merge Mammo) is a DICOM viewer geared towards mammography reading. By default, the data source you use for reading is the local machine, but you can add others -- and you can set up various DICOM nodes so it can transfer images between various studies. One big issue is that it is not promiscuous for transfers, so if the other machine doesn't know about you, you can't transfer. Actually, since the Query/Retrieve tool allows both a source and destination different than the local machine, you can use iReadmammo for transfer between two other machines.. As long as all three of them know each other.
<a href='http://trevoke.net/blog/wp-content/uploads/2009/01/ireadmammodatasource.rb'>This script</a> attempts to make life a little easier when first setting up the machine, by parsing two YAML config files (one for DB source, one for DICOM nodes) and adding them automatically. As an added bonus, there is the option of adding the new machine to remote hosts and scheduling a task to run at midnight to stop and restart the scriptservice (so the software reads the config again).
It requires the files 'ireadmammo_hosts.yml' (for Datasources) and 'DCconfig.yml' (for DICOM nodes), and if they don't exist in the same directory as the script, it'll offer to create them for you and allow you to configure them.
Error-checking is a little spotty, as I really wanted to finish the script at this point. It's the biggest thing I've written in several years.