#+TITLE: School creed
#+DATE: 2013-04-27
#+TAGS: martial arts, meditation, setting intention

In the dojo where I spent my formative years as a martial artist, there is a school creed. A quick search online has revealed that many schools have a similar creed. Every class says it as we begin, after bowing in, before calisthenics. I hear it and/or say it about three times per dojo night.

It's a simple creed, and clearly not unique. Here's what it says:
<blockquote>I intend to develop myself in a positive manner
and avoid anything that would reduce my mental
growth or physical health.
I intend to develop self-discipline, in order to
bring out the best in myself and others.
I intend to use what I learn in class
constructively and defensively, to help myself
and others and never be abusive or offensive.

&nbsp;</blockquote>
Kids and adults alike learn this creed and repeat it, together. All are taught to pronounce it powerfully, in the manner of an assertion. In that way, it is very similar to the few sentences American children have to repeat in their schools at the beginning of each day, and which sickened me for how similar it was to unadulterated brainwashing. Speaking of which, <a title="The Kafka Shuffle" href="http://the-programmers-stone.com/2008/01/05/the-kafka-shuffle/">this</a> is a very interesting and potentially disturbing read on the reading materials in school, but I digress.

Why do we make people repeat these words? We sometimes ask kids if they know what some words in there mean, like self-discipline. But certainly we're not teaching vocabulary to adults. So what's the point?

Well, the point is practice. These sentences are to be pronounced not only as assertions, but mindfully, pronouncing your desire to grow in that direction. They are simple precepts:
<ol>
        <li><span style="line-height: 13px;">Always aim for the things in life that will allow you to grow, always avoid the things that will make you shrink. Trick: sometimes you have to shrink in order to grow. Are those decisions mistakes? Are they following this code?</span></li>
        <li>Always try to be the best you can be, always try to allow others around you to be the best they can be. Trick: can you do both at the same time? Do you sometimes have to not be the best you can be to prod people into being the best they can be?</li>
        <li>What you are learning martially is meant for good. Possibly along the path of the Life-Giving Sword, but not necessarily. Simple application: don't get into bar fights. Trick application: everything you do must come from Love.</li>
</ol>
&nbsp;

This is intentionally left a little vague. Find your own questions. I'll answer.
