#+TITLE: Christopher Moore's Lamb
#+DATE: 2009-06-27 01:46:12 UTC
#+PUBLISHDATE: 2009-09-01
#+DRAFT: t
#+TAGS: untagged
#+DESCRIPTION: Well, I just finished the book. Apparentl

Well, I just finished the book. Apparently I do that with a lot of books - finish them at the wee hours of the morning.
"Alright.. I have half the book left to go.. I'll pick it up tomorrow."
"Alright.. I've got a quarter of the book left to go..."
"Well, only 35 pages..."

So, it's 2:30 am and in less than 8 hours I have to be beating up little kids.
Raven recommended Lamb by Christopher Moore.

I was really happy to have picked it up, and enjoyed reading about Jesus Christ as a child, and then as things evolved, I first really liked reading about the eastern religions. Then I realized things didn't fit. Some things about which I'm too young and stupid to have a sense of humor (like chronology and History) weren't right. There were some absolutely terrible puns.
Then it hit me that this idea of his wasn't really new - I'd read something quite similar in one of Aleister Crowley's books : <a href="http://www.leary.ru/download/crowley/%5BeBook%5D%20Aleister%20Crowley%20-%20Meditation.pdf">Meditation</a> Give it a read.

In the end, all the magic was gone from the book, and while I did enjoy the way it was written, and how well everything is put together, and how believable everything is.. It had become just a story.

I don't know what to think of the fact that I didn't get any new spiritual concepts from this book; I was kinda hoping I'd get something new. On a personal note, as I've thought and written somewhere before, I think now's the time for me to -do-.. Enough with the theorizing.

Thankfully, there's an epilogue in which Christopher Moore explains that he had to play with History and chronology, as well as scriptures and accepted "knowledge", to get things to fit the way he wanted them. It's not perfect and he apologizes.
There's even a second epilogue, because I bought a special edition (looks neat!), and he explains how he did it all, his trip to Israel, his thoughts during the trip...

Overall, I must admit, I'd probably recommend the book - it makes one smile, definitely -, but the epilogues really gave me a lot of respect for the author. And that was before he self-proclaimed a "not particularly devout Buddhist with Christian tendencies".