#+TITLE: A scene from a story: martial arts training
#+DATE: 2010-10-18
#+TAGS: story idea, fighting, martial arts, training, senses, mushin

The Master had been clear on this point - the room was treated so the five physical senses would be useless. When Scott asked how, the Master laughed and told him it was magic. Scott had chuckled and shaken his head. Clearly, no point in arguing - not today's knowledge.

Scott blinked and the test began. He relaxed and extended his consciousness into the ground below him and around him. He knew his limit well: no more than a five-foot radius around him. This meant that by the time he felt the opponent, it would be almost too late. Almost. The Master was sometimes annoyingly cl-

Scott flinched and his hips spun him around, hands flying up in an open, receptive guard position. An intrusion into the five-foot radius. It was almost like a physical blow to his solar plexus. He had felt the opponent. His mind started to rush through all the things he knew to do, and yet within an imperceptible lapse of time, his trained body took over with a quick, soft breath out.

The wind suddenly started to blow, and Scott mentally took notice of it. Wind in a room that had been magically sealed of the physical senses? He wasn't supposed to feel that. The blow he took under the floating ribs on the left side actually lifted him off the ground and sent him flying a few feet before landing hard on his pelvis. His mind had stopped and time hadn't. Fuck. Everything to start again. Actually... Scott realized he was still connected to Earth and could feel the opponent coming in. He stood up with a quick, hot breath that helped him expand Water and Air towards the other, feeling for the intent to strike, feeling for the movement, for the breath, for life.

Gotcha.

Connected, the movement became absolutely unimportant. For approximately half of one long, endless and yet very short second, everything in the room became one. When Scott's breath ended, the opponent was on the ground, stuck in a joint lock.

“What's with the wind,” Scott asked.

“Oh, just making sure your mind was in the right place.”

“Hardy har-har, Master.”
