#+TITLE: JetBlue - Don't use them (satisfactory ending)
#+DATE: 2010-11-18 10:42:10 UTC
#+PUBLISHDATE: 2010-11-23
#+DRAFT: t
#+TAGS: untagged
#+DESCRIPTION: So, a friend of mine made a reservation o

So, a friend of mine made a reservation on the same two JetBlue flights as me: 119, JFK-MSY, Nov. 10, 2010, and 120, MSY-JFK, Nov. 14, 2010. So far, so good. We get to JFK, I get my boarding pass swimmingly through one of the machines - but she gets a message that she needs to talk to someone. So, we do.

Now, let's go back in time a little. My friend, a French citizen and resident, was organizing a large trip. She made her reservations on September 25h, 2010 - approximately two months before the flight. On October 18th, 2010, her phone died. She was in Canada at the time, without budget to get it repaired or get a new one. She did, however, have easy and unfettered access to the Internet. That's approximately a month after the reservation. The evening before the flight (November 9th, 2010), she was with me, and received an email from JetBlue saying to do check-in automatically from home, like other companies do, and I received one just like it.  I, however, don't believe in printers, so there was no place to print the boarding pass. We therefore did not follow this course of action.

Now that this is out of the way... We talk to JetBlue employees, who, of course, have their hands bound and are powerless to do anything but tell us the following:

"The seat was reserved, but the payment did not go through. The notes on this ticket say that numerous attempts were made to call the person and rectify the situation."

So now, I ask you: really? THREE WHOLE WEEKS WENT BY before her phone died. She never received such a call. If calls were indeed made, did no one notice that the calls were going straight to voicemail? Did no one ponder the fact? How come no one tried to (GASP) send an email?

You know - I can forgive that. Weakness in the process and workflow. Those can be fixed. No worries. Let's just pay for the ticket now. Right?

WRONG. The seat is available, because reserved for her, but if she wants to board now, it's not the ~$220 that it was then, it is now ~$830. Yes. It's approximately four times as expensive. The choices were for her to take a cab back to my apartment and twiddle her thumbs for four days or for me to pay for her seat. If you think I forgot an option - I didn't. She could not afford to pay that amount.

Now.. I have just opened a complaint with JetBlue. The result of the complaint will determine whether this post stays up or not, and whether I actively discourage people (my company, my professional network, my friends, and their respective networks) from using JetBlue.

---------------------

Edit: JetBlue answered. Their original response was "Oh, sorry you guys screwed up, here's $100 dollars to be nice to you". Well, essentially. It was phrased, of course, politely and a bit differently, but that was the essence.

So I replied and told them in no uncertain terms that it was, indeed, them who fucked up, and gave them a few ideas as to how they could have handled the process differently to avoid the fuck-up. I also told them that I had a worldwide extensive network of social and professional contacts and I would launch a crusade against JetBlue if I didn't get my money back.

... Yes, I used the word crusade. Yes, I smiled when I wrote that.

A few hours later, I got another message from them refunding the extra cost - so the seat only cost the original fare instead of 2.5x the price. I'm not going to start my crusade. I'm pretty happy about that, because I wasn't sure what the karmic debt would be, on their side and mine. And, of course, my friend still has the $100 credit they put on her JetBlue account, since they probably can't take that back.

I'm pretty sure we're still going to avoid JetBlue in the future, but as far as what YOU should do.. It's up to you :)