#+TITLE: Who follows who?
#+DATE: 2009-03-26 20:36:29 UTC
#+PUBLISHDATE: 2009-03-26
#+DRAFT: t
#+TAGS: untagged
#+DESCRIPTION: In the past couple of weeks, I'd gotten t

In the past couple of weeks, I'd gotten to spar progressively harder with a blue belt who is twice my age, but has been in dojos where sparring and self-defense were more important than kata. As a result, I consider him somewhat dangerous to spar with.. And, well, I let myself get caught up. I stopped being the watcher..
I hid behind the excuse that I was just sparring as hard as he wanted to spar, and so it just escalated.
Yesterday I took a different approach; I resolved to work on what I wanted to work, which turns out to be distance/range evaluation and shifting.. And I sparred at half-speed. He followed my speed, only speeding up a little as he got into it. I did not.
I asked him after sparring what he thought of the first minute or so of sparring with me, and he said he didn't remember much.. But it enlightened me to hear "At first, I always take a few seconds to see if we're going hard or soft, and then I get going".
Here I was, thinking I was following him, and here he was, thinking he was following me! It sure is a good thing I took a step back from the vicious cycle.