#+TITLE: Gentoo on a Dell Inspiron Mini 10
#+DATE: 2010-03-01
#+CATEGORIES: sysadmin
#+TAGS: gentoo dell-inspiron-mini-10

There are a few gotchas:

1) If you have a SSD drive, you need to <em>modprobe pata_sch</em> to see it.
2) when using GRUB, install it on whatever drive the hard drive is, even if it's /dev/sdc -- and let your FSTAB use /dev/sda. Chances are that /dev/sda is your liveUSB.
3) In the kernel, in the I2C options, don't let it pick automatically - instead, select the algorithm options in the menu that appears (I don't know it off-hand, will edit this post later to add the important information). This will allow you to install the kernel driver for the poulsbo card (kmod-psb, I believe).

For the rest, so far, it seems that the howto on the Gentoo wiki is good. I installed e17 very painlessly.

Wireless was a bit trickier.
I needed to use gentoo-sources-2.6.33, which at the time of this writing was masked as ~x86. A big advantage though is that it has support for the Atom processor (and the proper driver for the broadcom card!).
Enable the "B43" driver in the kernel.
Then, follow the instructions given <a href="http://linuxwireless.org/en/users/Drivers/b43#fw-b43-lp">here</a>:


#+BEGIN_SRC
git clone http://git.bu3sch.de/git/b43-tools.git
cd b43-tools/fwcutter
make
cd ..
#+END_SRC

Use version 4.174.64.19 of Broadcom's proprietary driver. (The tarball is mislabeled as "4.178.10.4", but it is actually 4.174.64.19.)

Download and extract the firmware from this driver tarball (Gentoo's installation directory for this is /lib/firmware):


#+BEGIN_SRC
export FIRMWARE_INSTALL_DIR="/lib/firmware"
wget http://downloads.openwrt.org/sources/broadcom-wl-4.178.10.4.tar.bz2
tar xjf broadcom-wl-4.178.10.4.tar.bz2
cd broadcom-wl-4.178.10.4/linux
sudo ../../fwcutter/b43-fwcutter -w "$FIRMWARE_INSTALL_DIR" wl_apsta.o
#+END_SRC


At the time of this writing, although the b43-firmware is available and promises to give us what we need, the b43-fwcutter tool is only at version 12, and not 13, so it can't be used. This is why we need to use <em>git</em> to download the latest version and correctly build the firmware by hand.
