#+TITLE: So, you want to spar?
#+DATE: 2008-03-21 15:27:53 UTC
#+PUBLISHDATE: 2008-03-21
#+DRAFT: t
#+TAGS: untagged
#+DESCRIPTION:  Sparring can be one of the many reasons 

 Sparring can be one of the many reasons one wants to join a martial arts school, sometimes even their only interest. Unless you join a school based on street defense, you may not do as much as you'd like. Besides, the insurances and legality issues being what they are, usually you are limited to sparring gear which lets you mostly throw punches and kicks.

The teacher of a traditional school probably won't let you spar until after you get a belt or two, because you need to break in your body and the techniques you are learning -- besides, you don't have enough control to know when to stop your strikes, so if your opponent fails to block, you could hurt him quite a bit. It's more dangerous to spar a beginner than an advanced student :) Sparring will teach you footwork and will get you used to seeing strikes come at you. It'll also get you used to working out combinations of strikes, pacing yourself, and speed of action.

What is more important to value properly, in my opinion, is the study of applications from forms, or the study of self-defense moves (whichever it is called in your school). There, you learn to apply the defense against a helpful opponent, slow at first, then increasing the speed, then increasing power, then with a less helpful opponent. This is when you get a chance to really program yourself and get your neural connections solidly prepared, as well as use your body to manipulate the opponent's body.

Of course, sparring is very important as well, and a school that doesn't do any of it had better have other exercises to compensate for the values taught during sparring.

In the end, it's importan to remember that sparring isn't about beating up the other guy, much less about winning. Rather, it is about working with your partner to improve your technique as well as his, in a positive and safe environment where you can prepare for something you probably hope you'll never have to use.