#+TITLE: Body weights
#+DATE: 2009-07-05 17:46:44 UTC
#+PUBLISHDATE: 2009-07-05
#+DRAFT: t
#+TAGS: untagged
#+DESCRIPTION: I found some body weights that can be car

I found some body weights that can be carried under regular clothing. This is my review of them.
Pictures are at the following gallery: http://trevoke.net/gallery/thumbnails.php?album=12
<!--more-->
Here are the different options, with first the size, then the weight. To figure out which size is good for you, measure the widest part of your forearm or leg.

<strong>Arm, Small / Medium</strong>: 8" - 11" ; 2lb 12oz
<strong>Arm, Large / Extra-Large</strong>: 11" - 14" ; 3lb 7oz
<strong>Leg, Small</strong>: 11"15 - 13" ; 2lb 13oz
<strong>Leg, Medium</strong>: 13" - 14"5 ; 4lb 6oz
<strong>Leg, Large</strong>: 14"5 - 16" ; 5lb 0oz
<strong>Leg, Extra-Large</strong>: 16" - 18" ; 6lb 13oz

I measured and bought pairs. My calves are ~17" around so I bought XL legs, and my arms were a teeny bit over 11" so I bought the L/XL arms. The arms were a mistake, I should have taken the size below, I think. I'd need to build muscle to hold them well.

I wore a set (arms + legs) for a full day at work with minor or nil inconvenience (I was just a little hungrier than usual). I used them for running and jumping rope. They support non-sudden movements very, very well, and the leg weights did nothing unexpected or annoying doing the rope jumping.
I study isshinryu, which is a system which uses speed and snap in its strikes. The leg weights did fine in the kicking tests, but during the punching tests, the weights all crumpled up in a lump close to my wrist. It's better if I wear something like a tennis sweatband close to my elbow to hold the weights there.

Men, put your egos at the door - I purchased them at a website called 'As we change', for women's fitness.
<a href=http://www.aswechange.com/AsWeChange/Shopping/ProductDetail.aspx?CID=Fitness+%26+Weight+Mgmt&SCID=Fitness+Equipment&ProductID=327775&SourceCode=80509000002&mr%3areferralID=09920e0a-606d-11de-a563-000423bb4e95>Arms</a>
<a href=http://www.aswechange.com/AsWeChange/Shopping/ProductDetail.aspx?CID=Fitness+%26+Weight+Mgmt&SCID=Fitness+Equipment&ProductID=327776&SourceCode=80509000002&mr%3areferralID=09920e0a-606d-11de-a563-000423bb4e95>Legs</a>

I don't think they really are meant for muscle-building, more for calorie-burning, but they can be used during regular training under your uniform. I will keep experimenting with them, and I would appreciate ideas as far as things to try with them on :-)