#+TITLE: Another awesome training evening
#+DATE: 2009-09-17
#+TAGS: martial arts, pain

So tonight, I went to train 35 minutes away from home, at the dojo where my sensei's sensei teaches. Warmups / stretches, kicking drills, calisthenics, sparring, then fighting drills.
Sensei's sensei has a son who is now 48. Now -- I am fast by normal people's standards. This guy is really fast by my standards. He also has a really positive energy - very friendly eyes, a great disposition.. And he can dislocate your jaw before you can blink or think "oh sh..!", so don't piss him off.
Anyway, as much as shihan (sensei's sensei) is amazing, tall, skilled, talented, dedicated to his art, as much his son inherited many of the traits, has been training under his dad a long time, and has learned a lot from a ton of sparring and tournaments and just .. being there.
So now he imparts his wisdom and skills, and it's WONDERFUL to watch him in action, and learn from him, and listen to his way of explaining things. Just like in Dune, "A process cannot be understood by stopping it", he explains action and reaction within the context of a moving match, which is AWESOME.

I breathe hard when I'm in this class. It's a bit of a work-out, and excellent cardio.
Oh ! So shihan's son hit me twice, and I managed to shift out of the way of the third strike, like I felt his movement and reacted. It was sweet. Now I only need to make that happen ALL THE TIME.
