#+TITLE: Spending energy uselessly
#+DATE: 2009-09-01 17:59:31 UTC
#+PUBLISHDATE: 2009-09-01
#+DRAFT: t
#+TAGS: untagged
#+DESCRIPTION: I live on an island. It only took me unti

I live on an island. It only took me until last week (10 years and change) to take my dad's advice to go to the beach when I felt like it. So I did that, last week and today, and went swimming. Good for the muscles, good all-around body work. Great stretching. Different way of using the muscles.

Besides the fact that I could really only swim for 10-15 minutes before I was tired and a part of my arms started to ache (indicating, clearly, that I'd been ignoring it), I noticed on my way home that even just 30 minutes at the beach drained me of energy. The 'new' situation was interesting, I was very aware of everything, and I spent a lot of energy on focus which did not need to be spent. It'll be a learning curve. It's a shame autumn is upon us.

On another note, I am finding sand in my hair, and am reminded of my childhood. It is a good feeling.