#+TITLE: Testing for purple
#+DATE: 2008-05-01
#+CATEGORIES: martial-arts
#+TAGS: belt-test

Monday and yesterday, two blue belts were to test for purple. They went through their calisthenics and basics; I did not see their forms on Monday, but I did see them on Wednesday. They were bad enough sensei wanted to see them again, that much I understood, but not sure how bad until I saw them both.

Neither of them broke a sweat until fighting, not for the 100 jumping jacks, not for the 60 push-ups, not for the multiple kick combinations. They did get out of breath when doing all the forms in a row, at least...

Neither displayed the spirit we expected from a blue belt.. Let alone from someone testing. A test is supposed to be the hardest thing you've done to date and you're supposed to work as hard as you can.. And that's usually noticeable. Further, their forms weren't even up to blue belt level. Chances are they did not practice outside the dojo.. Or even think about the art at all. While some people do martial arts leisurely, you should either expect to stop progressing or realize that work needs to go into it.

One of the blue belts seemed OK with the postponement and stayed to speak with sensei.. The other one pretty much stormed out.. Well, we'll see what happens now.
You have to TRAIN !
