#+TITLE: Society's focus on knowledge
#+DATE: 2011-10-20 08:23:34 UTC
#+PUBLISHDATE: 2011-10-20
#+DRAFT: t
#+TAGS: untagged
#+DESCRIPTION: Here is a thought with which I've been wr

Here is a thought with which I've been wrestling for quite a while - the focus of society on knowledge and what it could be doing to us as people, human beings, and members of society, as well as to society itself.
<h4><strong>Knowledge is power</strong><em> - knowing more can only help you</em></h4>
In the West (bounded to the east by Russia and to the west by the Americas), the focus has historically been on developing more knowledge, more science. Two interesting examples could be the game Civilization, where you need to develop science to be able to stay afloat with the other competitions, or the Cold War, where both the US and the USSR were struggling to stay ahead of each other in an arms race, because the better weapon would force the opponent to abdicate.
<h4>A little knowledge is a dangerous thing (you only have enough rope to hang yourself with)</h4>
<h4>power corrupts (so when you have knowledge...)</h4>
Gaber - Il dente della conoscenza - knowledge, culture, science, power

Society and the focus on knowledge - the society ignores the body (obvious focus on first world, computers, etc - physical jobs still exist, like construction, but ignored for the purposes of this post - talk about the trend, not the absolute).

So where are we going?