#+TITLE: The Tooth of Knowledge (Lyrics)
#+DATE: 2012-04-26
#+categories[]: philosophy
#+tags[]: lyrics knowledge

This song is at least as old as 1973 and is originally from Italy (Giorgio Gaber - Dente della conoscenza). If you like finding patterns, making analogies and metaphors, and overall pondering, then examine the tooth of knowledge in the contexts of: science, religion, culture, society (etiquette, etc), and finally, the internet.

&nbsp;

(note : 'SHHH' is an inhaling sound)

‘TICK’ and then ‘SHHH’,
‘TICK’ and then ‘SHHH’,
‘TICK’ and then ‘SHHH’,
‘TICK’ and then ‘SHHH’,
‘TICK’ and then ‘SHHH’.

In a random place, you can say anywhere,
it really seems that a child was born,
it's a normal child, not very special,
except for the fact that it has a strance tooth
and he does ‘TICK’ and then ‘SHHH’,
‘TICK’ and then ‘SHHH’.

Neither the mom or the doctors know what it is,
it's not foreseen by science,
To understand one another we'll call this anomaly
The Tooth of Knowledge.

‘TICK’ and then ‘SHHH’,
‘TICK’ and then ‘SHHH’.

In his tower, all ivory,
the genius studies his maps
concentration, inspiration,
his culture, his art.

In a normal tooth there's no harm,
but by some stroke of fate
data tells us that other children were born
all of them with the same tooth
and they do ‘TICK’ and then ‘SHHH’,
‘TICK’ and then ‘SHHH’.

There are those who say that this tooth is the guarantee
of a precocious adolescence,
they're allergic to their mother's milk
but they suck up knowledge
and they do ‘TICK’ and they do ‘SHHH’,
‘TICK’ and then ‘SHHH’.

In his tower, the genius studies
the reason for these teeth,
he looks at the problem technically
and suggests they get removed.

There they are in front of you with their small teeth,
it really seems that your blood attracts them,
they don't go to school, they don't read books,
they give bites like the vampires do
and they do ‘TICK’ and then ‘SHHH’,
‘TICK’ and then ‘SHHH’.

And when they suck, they learn everything you know,
they level intelligence.
Culture and its power are now in crisis
with the Tooth of Knowledge.

They've surrounded even the tower,
the genius screams that he doesn't want it,
they sucked a bit of his blood,
they haven't even hurt him,
but now they already know everything that he does,
He hadn't realized it
he lost his power, he's a man like us...
