#+TITLE: Which martial arts school is right for you?
#+DATE: 2008-03-20
#+TAGS: martial arts

So, you've decided to start taking a martial arts class. Good for you!

Why do you want to join? Is it to fight, to learn to defend yourself, to develop self-discipline, to learn kata ('forms'), for health reasons? All of the above?

For the purpose of this article (if nothing else), I will make a differentiation between a fighting style and a martial art. In a fighting style, you are learning to fight, and that is it. Martial arts involve other lessons.

There are many martial arts. Karate is but one genre, and within that genre there are many styles, just like chuan fa (usually mistakenly called kung fu). They all have the same goal, but the path is different. Another important difference is that some fighting styles/martial arts are better fit for a body type than another. While you will be limited by what is in your area, that is something you will need to keep in mind. It is possible to study any style without great handicap, but you may have to work a little harder. With any luck, the teacher at the school will be knowledgeable enough to tell you this in greater detail.

This brings me to the next important point - the teacher. It is in fact more important than the style you choose to study, because a teacher makes or breaks a school (and his/her students). Do talk to the teacher beforehand, and pay particular attention to anything that sounds like the teacher has an agenda other than to teach you as best as he/she can. Maybe the teacher needs to prove their strength or skill. Maybe the teacher doesn't like men, or women. Maybe the teacher just wants your money..
Ask for a trial class, if it is not specifically offered. Ask which is a good day to come - some schools pick days of the week to practice certain things, and watching a whole hour of people in gear sparring may not be the best thing if you are looking for a school that teaches forms - even if said school excels at teaching forms, and you came for the wrong trial class.

When you are there, pay attention to the interaction between students, pay attention to the top students' behavior, and pay attention to the teacher's words. Watching students will tell you how they feel about the school. Watching the top student is usually a good indicator of what is likely to happen to you if you stay with the teacher long enough. Watching the intermediate students will tell you what is likely to happen in a year, or two, or five - and that's important too! Watching the teacher will tell you what you're in for, even though all teachers are likely to be extra-nice if a new potential student shows up. Pay particular attention to the atmosphere - if you will be training there, you will most likely be there for a long, long time, and you definitely want a healthy atmosphere.

Last but not least for this small introduction, YOUR responsibility!
Once you have chosen a teacher and a school, you MUST enter as a <em>tabula rasa</em>, a blank slate. Whatever you know, or think you know, you must discard it so as to learn exactly what you are taught there.
If you can't make it to a class, do call - it is polite, and your teacher won't worry about you.
Also, and this comes more naturally with practice, focus your mind only on martial arts when you are there. It makes your practice time purer, it improves the atmosphere of the dojo, and it helps your mental discipline.

I hope this helps - good luck in your training!
