#+TITLE: Why do I study martial arts?
#+DATE: 2009-10-03 17:28:47 UTC
#+PUBLISHDATE: 2009-10-03
#+DRAFT: t
#+TAGS: untagged
#+DESCRIPTION: I am watching Rocky III and IV (the only 

I am watching Rocky III and IV (the only ones I really like), and the driving theme is the power of the human spirit. Rewatching it now, I see a lot of other ideas. They're not particularly hidden, but I never really noticed them before. This started to make me think about my choices.
<!--more-->
My lasting decision to study martial arts was made in college, and I took a Physical Education class of self-defense taught by shifu Christopher Goedecke, who studies and teaches isshin kempo. During the first class, we sat and he asked us why we chose to study martial arts. My answer was, "I want to develop discipline over my mind and body."
I can tell you today that this answer was probably not the truth. It was probably what I thought shifu wanted to hear so he'd think that I was special, or would be a good, dedicated student.
Why this behavior? Saying that everyone wants to be special would be a bit of a cop-out answer here. I always, always liked the idea of the martial arts, and the dedication, the Way.
A more refined thought is that I wanted a mentor. A senior figure I could respect, who could teach me and guide me. For all my mental independence and ambition, I want to be somebody's pupil.
When I was barely beginning, I had the self-centered thought that shifu Goedecke would instantly take a liking to me and take me under his wing. I was, what, 20 years old or so? Most of my thoughts back then were self-centered. For that matter, most of them now are, too.

I graduated, and shifu Goedecke told me it was silly to drive two hours each way for a class, that I should find a teacher closer to me, and that we'd see what the future brought. I dutifully did so, and found sensei Marilyn Fierro, who teaches and studies isshinryu karate. I'll skip all the martial arts lineage drama. Isshin kempo and isshinryu karate have close ties, so I found the same kata (forms), and I did not have to relearn everything from scratch.

I joined the dojo and studied for a few years with no questions, no doubts. I reached the rank of first degree black belt, and kept on studying. As I near the exam for second degree black belt, questions appear. The timing, as far as belt tests, is possibly coincidental. As the rest of life happened around me and to me, and as I looked at my behavior, and how I felt about things.. Questions appeared. As my view of the world becomes less self-centered - as the world grows beyond my belly button and encompasses others, and as I become aware more fully of other people, I see how I relate to other people.

So.. Why do I study martial arts? In a world and a society where fighters are a specific group of people, and the average person doesn't fight, why? In a world where a living is made from the product of thoughts.. Why a physical discipline? What is the point?
I always believed in a society, or a social circle, or at least people who would accept and respect each other based on a similar culture, mindset, and skillset. I see this happen in the hacker/programmer culture and in the martial arts culture. This being said, I'm only talking about martial arts here.
So, I want to just be me and my skills, and not be respected for some other reason. And someday, I believe it'll happen. It's a long way up, but that's the point - that skill cannot be faked.

So now, we come to a major doubt of mine, something that's been nurtured for a while and which is the ghost I now need to face.
As an introduction, we have the Rocky movies, and there's a manga called 'The Breaker' which I am reading, as recommended by a friend of mine. That manga talks about a kid who apparently has no physical skill, no innate ki, but develops tremendous spirit, determination, mental resistance, and learns through that. At the point where I am in the movie, he fights a kid who is a super-genius of the martial arts, has mastered five at the age of fifteen, has amazing amounts of ki and physical prowess, and is essentially perfect - but he relies on logic and doesn't really understand the power of sheer spirit.

Well. As the second degree exam approaches... Slowly but surely, my training has become a little more intense, and I have felt things become more difficult. And I don't like it. I do it, but I don't like it. I am naturally a lazy person, and I want to change that. I just don't put in that much effort. I rely on the fact that I am naturally 'good enough'. I want to change that. I want to push myself further. But where's my spirit? My will to not stop when it hurts? I've always lacked that. Oh - I don't mean that I am a wuss, but ... I doubt myself.

There has been improvement. I will not deny it. I have seen myself improve. I can stretch further than I used to, more than I used to.. I can do more push-ups, my stamina's improved. I can do more.. But it's not enough. I need to be more. More. More. Always more.

I get the feeling I'm reaching my limit. And this feeling has to be a mental block, an illusion. It can't be real, but it seems so real. How do I get rid of this? Ugh. How do I convince myself that my limit is further away? 