#+TITLE: Learning and fear
#+DATE: 2013-11-18
#+TAGS: learning, fear, junot diaz

<blockquote>
<div>“Life is going to present to you a series of transformations. And the point of education should be to transform you. To teach you how to be transformed so you can ride the waves as they come. But today, the point of education is not education. It’s accreditation. The more accreditation you have, the more money you make. That’s the instrumental logic of neoliberalism. And this instrumental logic comes wrapped in an envelope of fear. And my Ivy League, my MIT students are the same. All I feel coming off of my students is fear. That if you slip up in school, if you get one bad grade, if you make one fucking mistake, the great train of wealth will leave you behind. And that’s the logic of accreditation. If you’re at Yale, you’re in the smartest 1% in the world. […] And the brightest students in the world are learning in fear. I feel it rolling off of you in waves. But you can’t learn when you’re afraid. You cannot be transformed when you are afraid.”</div>
<div></div>
<div>- Junot Diaz, from a recent speech at Yale</div></blockquote>
<div>If you spend more than an hour with me in person, the chances of me mentioning Dune increase asymptotically. So it shouldn't be any surprise that this quote brought to mind two quotes from Dune, and here they are.</div>
<blockquote>
<div>Muad'Dib learned rapidly because his first training was in how to learn. And the first lesson of all was the basic trust that he could learn. It's shocking to find how many people do not believe they can learn, and how many more believe learning to be difficult. Muad'Dib knew that every experience carries its lesson.</div></blockquote>
<div>And the other one, well, I wrote a blog entry about..</div>
<blockquote>
<div><a title="The Litany Against Fear" href="http://trevoke.net/blog/2013/11/18/the-litany-against-fear/">I must not fear.</a> Fear is the mind-killer. Fear is the little-death that brings total obliteration. I will face my fear. I will permit it to pass over me and through me. And when it has gone past I will turn the inner eye to see its path. Where the fear has gone there will be nothing. Only I will remain.</div></blockquote>
<div></div>
<div>    I hadn't really thought of connecting these two before, even though to me they are some of the most important quotes in the entire work.</div>
<div>    It does make sense though. It takes a fundamental trust in oneself to learn, and when you are afraid, you are basically robbed of that fundamental trust. So if Junot is right, and he probably is, since he lives in the educational system, there is a deep flaw in the system which is in fact making it harder for students to learn.</div>
<div>    When a system grows, sometimes a madness creeps in. Like Terry Pratchett wrote, "<em>[a dangerous thought is that] while all important enterprises need careful organization, it is the organization that needs organizing, rather than the enterprise.</em>" So, after a while, it's less about the students learning and more about the grades, and then it's more about making sure the teachers do their work. But how do you make sure teachers do work? Ah-ha! There's a thought. Let's organize THAT. And the students? Well, they're in school, they'll learn, right? And so it begins. Subtly. Insidiously.</div>
<div></div>
<div>    As students, resisting that pressure is very difficult, but if you can, if you're able to put it out of your mind, if you're able to recognize it and not let it crush you, then you can truly learn, truly get an education. Truly be transformed, as Junot puts it. And the result will always be a marvel.</div>
