#+TITLE: Sparring
#+DATE: 2013-05-15
#+CATEGORIES: martial-arts
#+TAGS: sparring

<h1>What Sparring Is</h1>
Sparring is a playful and explorative interaction.

Sparring is an exercise, a drill. The Japanese use the word KUMITE - which basically means "grouped hands" or "pair hands", "joined hands", "hands together" (the Wikipedia article suggests "grappling hands").

Sparring is a two-person free-form exercise wherein you get to examine scenarios involving combinations, footwork, distancing, rhythm, controlled power, and focus to improve yourself and your partner.

<!--more-->

<strong>Combinations</strong>: you get to play first-hand with things you have learned and put them in an environment where there is no set response. You learn what the combination does and what it does not do. You get a feel for when to use it, when not to use it. You will also learn not to stop after a single strike. WOOHOO you got a strike in! So what? Get in another one and another one! Learn how to use feints and setups for your combinations.

<strong>Footwork</strong>: sliding along a line, stepping around. When to change your front foot, when not to. When to step, when not to. This is harder than it sounds when you only have a split-second to make the decision.

<strong>Distancing</strong>: You can draw two concentric circles around an immobile person, representing the reach of their arms and legs. You learn how far your strikes go depending on your stance, you learn when the opponent is entering your zone and when they're dancing just outside of it. You learn where your partner's zone is. You will learn to enter and leave the opponent's zone, <em>and when to do so</em>.

<strong>Rhythm</strong>: people have a rhythm (let's leave the no-rhythm stepping of the Fremen out of this for a second). Controlling the fight can be done by means of controlling this rhythm. Anything you do between those beats is either invisible or unavoidable to the person. Someone who is jumping up and down is most vulnerable right before they land. Someone who takes a step forward is vulnerable when they are transferring the weight to the foot if it's still up in the air.

<strong>Power</strong>: sparring is not about power generation, because unless your partner is much better than you are, you're eventually going to hurt your partner, and they're not going to want to train with you again, which probably defeats the whole purpose, because when you run out of training partners, you've got no one to spar with. If both players have a solid understanding and agreement, then you CAN use power. I've been in a few very fun sparring matches like that, very exhilarating experiences where the speed and the power was way up. Because both of us were playing and exploring, and we had a clear agreement and understanding on the goal of the drill, it was fine. You can and should develop power - however, this is done with other drills.

<strong>Focus</strong>: Alright, so we are not going to use full power. <strong>We're still going to throw quick and precise strikes and we're still going to make solid contact.</strong> While we're not doing point-sparring, we're still sparring, and a solid strike counts as a strike that could have been much more powerful; in proper point sparring, that's a point - not touching someone with your toe. So, you should always honor the strike as being a real strike if it had the proper focus/kime, etc. It's of course OK to smack down a round-house that made contact weakly, because it would have just been a touch. That is part of the contract. 'Contact' does not mean 'hit' if it does not have focus.

Now, having said all this, full-contact sparring has all the same things, but they don't limit the power. <strong>Full-contact, full-speed sparring is practiced in systems where significant body conditioning occurs. This is not a coincidence.</strong>
<h1>What Sparring Is Not</h1>
<div>Sparring is not a fight. Sparring is not a competition. If you or your partner try to win, then the purpose of the drill is defeated.</div>
If you consider sparring to be a practice fight, then all of a sudden it's OK to hurt someone - because that's what you're practicing. Sure, it's not knitting class, but sparring is not about hurting someone. And it's not about winning.

Why are we wearing gloves? Headgear? A mouthpiece?  These aren't excuses to hit someone harder. They are there to protect YOUR body, not the opponent's. They are worn by both people because you are training something dangerous, in which mistakes happen. The Pavlovian response to putting on gloves should not be "Yeah! Time to waste something!", it should be "Time to make sure I am fully alert."

There are two excellent articles coming from the world of the Russian martial art called Systema. The first is called <a title="The Kickboxing Trap" href="http://russianmartialart.org/ikfkicktrap.html" target="_blank">The Kickboxing Trap</a>. It talks about the following three traps:
<ol>
        <li><em>Trying NOT to lose</em> (which is not exactly trying to win, but equally dangerous and much more subtle)</li>
        <li><em>Trying to move faster than the opponent </em>(in Systema, sparring is done at a slower speed)</li>
        <li><em>Having undefined goals</em> (WHY are you sparring? Which aspect of your practice are you working on improving?)</li>
</ol>
You should go read it.

The second article is called <a title="Slow Sparring Game of Russian Martial Arts" href="http://www.dojoofthefourwinds.com/sparring.html" target="_blank">Slow Sparring Game Of Russian Martial Arts</a>. I will give an excerpt here to give you an idea of a particular and very effective method of sparring (I know this from experience). In the following excerpt, emphasis is mine.
<blockquote>The basic premise of the Slow Sparring Game (SSG) is <strong>to create an environment where all technical aspects of hand to hand combat can be explored in relative safety</strong>, while providing the body a chance to execute and cultivate true spontaneity. To facilitate this, the <strong>SSG must be viewed as a slow motion representation of combat</strong>.</blockquote>
Here are some things it talks about:
<ol>
        <li><span style="line-height: 13px;">Changing speed, whether speeding up or slowing down during the movement</span></li>
        <li>Changing trajectory, just because you can when you're going slow</li>
        <li>The defender moving faster than the attacker</li>
</ol>
You should go read it.
<div></div>
<div>
<h1>How to get good at sparring</h1>
There's no secret, no magic formula. You gotta spar. <strong>You have to spar while being fully alert and cognizant of all those things</strong>. What if you've learned to spar already, but what you really learned was how to beat down (or how to be afraid of the other person) ? Then you have to spend time being extra-aware, with partners who will be understanding, and you probably should slow down even more than you otherwise would, because I can guarantee you from experience that you'll speed up, because you'll get afraid or uncomfortable or angry or competitive. It happens. And it's nothing to be ashamed about. People make mistakes. We all do. But you have to be in there with the intent of improving and helping your partner improve, with an open mind.
<h1>What if someone breaks the agreement?</h1>
This, for better or for worse, depends on the culture in your environment.

If they break the agreement because they are trying to fix their habits, be patient, take breaks, talk to them. Be aware of when they get scared or uncomfortable and ease up on the pressure.

If they break the agreement because they don't believe in it, then I would say, don't spar with them. Have them read this blog post and have a conversation with them about it. Send them to a Systema school for a little while so they learn that speed and power aren't the main elements in a fight. Or, if you're much better than they are, let them get frustrated and angry and beat themselves against the wall. Eventually they'll get tired of fighting. Every once in a while, people meet a problem and they have to burn all their Yang before they realize that it's easier to be Yin.
<h1>Other Valuable Information</h1>
<h2></h2>
<h2>Teacher-student relationships when sparring</h2>
Sparring can be a very effective teaching tool: you can give students the proper positive feedback for a good strike, and the proper feedback (or lack thereof) for an improper strike. You can teach them to find openings, to think in circles (or spheres), to recognize rhythm. And if you're really good - you'll do it without speaking. You can choose to interrupt the sparring regularly to examine the current situation at more leisure. Sometimes it's necessary to slow things down.
<h2>Differences in experience levels</h2>
<em>The more-experienced player should only ever answer with 80% of the power of the less-experienced player.</em> The more-experienced player should not be punishing or otherwise bullying the lower-experienced player. There are further lessons to be learned there by the more-experienced player, which I will not discuss here, because it might be a spoiler, and some of this stuff you really should learn by doing.
<h2>What not to learn from watching high-experience players</h2>
Higher-experience people who are sparring together may seem to be ignoring such strikes, most likely because they're working on other things, like the focus, the rhythm, the continuity of motion, etc., it does not mean it is OK to ignore these strikes. They are (or should be) acknowledging the strikes, storing the experience in memory to learn from it later, and continuing.
<h1>Conclusion</h1>
Sparring is, or should be, a very enjoyable activity. It is a time where you can learn much about yourself and about your opponent (cue <a title="Seraph vs. Neo" href="http://www.youtube.com/watch?feature=player_detailpage&amp;v=TDhLXkRhg60#t=90s" target="_blank">Matrix reference</a> - I was the only one laughing in the theater when this happened...). It is a time where you drop all pretenses, drop your ego, and just get to be, along with your partner. My best friends are my best sparring partners, and this is not a coincidence.

Proper sparring requires a set of agreements between all parties, and tremendous mindfulness. Thankfully, the payoffs are huge. With proper sparring, you will grow intellectually and emotionally and, if that's not enough for you, your martial skills will also improve

Much can be learned during sparring. Usually after the fact. I can think of a handful of occasions where something happened and, during a pause, one of us said "Oh, that move came from kata X" or "I've been practicing Y and I had no idea what it was for - now I do!"

So, to steal unashamedly from a great man... <a title="UnderstandGoodPlay - the book" href="http://www.bushinbooks.com/about.html" target="_blank">Understand? Good. Play!</a>

</div>
