#+TITLE:       How to run retrospectives
#+AUTHOR:      Aldric Giacomoni
#+EMAIL:       trevoke@gmail.com
#+DATE: 2016-04-26
#+URI:         /blog/%y/%m/%d/how-to-run-retrospectives
#+tags[]: retrospectives
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: How to run retrospectives
#+DRAFT: t

* Howto: run retrospectives
A successful retrospective is one that fulfills its function. The function of a retrospective is to find ways for the team to get its work done more efficiently.

* The steps of a retrospective
- Everyone verbally agrees to the Prime Directive
- Check in on last retrospective's objective(s): did they get accomplished? Should we continue with these changes?
- Pick conversation topic
- Explore root causes
- Converge on action item(s)
- Pick one champion for each action item
- Retrospective the retrospective

 A longer and excellent explanation of these topics can be found in James Shore's Art of Agile Development book. The chapter on Retrospectives is available [[http://www.jamesshore.com/Agile-Book/retrospectives.html][online]]. What you are about to read assumes that you are familiar with these ideas already.

* The facilitator's role
The facilitator has one fundamental responsibility: to lead the team through the steps of the retrospective while maintaining the safety of the space.

The facilitator must:

- Manage the tensions of the conversations
- Be cognizant of the time
- Give only as much information as you need to
- Allow everyone to be involved
- Be ready for emotions to surface
- Allow the team to come to its own decisions

* Manage the tensions of the conversation
There are divergent and convergent steps in succession. For example, generating ideas is divergent, grouping is convergent. Exploring root cause is divergent and has a subtle convergence to it: threads should aim for some kind of explanation. Finding an action item is convergent.
* Be cognizant of the time
 The meeting starts and ends at scheduled times. If it starts late, it'll still end on time. A retrospective isn't a free pass for a time-out. It's still work.
* Give only as much information as you need to
Say absolutely as little as possible to give the team the maximum amount of time. Everything you say eats into the team's time and mindspace. Let the team focus on what they need to think about.
Understanding the retrospective must not take the place of making the retrospective happen. Explain only what you need to. At the most, explain the prime directive, the goal, the format, and then get on with the retrospective.
* Allow everyone to be involved
Make sure everyone gets a fair share of the conversation. It doesn't mean equal -- but it means that if someone has something to say, it should be heard. Among other things, saying something "wrong" or "stupid" should be completely acceptable (ie nothing is wrong or stupid).
A retrospective is a time for change. Change is hard. Team members *must* be able to say what's on their mind.
* Be ready for emotions to surface
Chances are, at least one person in the room cares a lot. Maybe someone felt slighted. Communication in a team isn't always great, and many people take this work personally. Anger, sadness, bitterness, cynicism.. These can all come out. Be accepting and gentle. Sometimes the team, or someone in the team, will shut down that person. Don't let that happen.
* Allow the team to come to its own decisions
The facilitator does *not* make decisions for the team. Let *them* do it. They know what they're working on way better than you do, and they know the pains they feel way better than you do. Make sure everyone is empowered to participate in the decision-making process.
